### ISSUE TITLE
cannot find -lLLVMTransformUtils 

### ISSUE THREAD

**Issue by lkmidas** [bluesadi/Pluto-Obfuscator#1]
Hi, I've recently built this project and ran into the following issues: 
- the line `link_libraries("libLLVMTransformUtils.so")` in `Transforms/CMakeLists.txt` results in `/usr/bin/ld: cannot find -lLLVMTransformUtils` and so `LLVMObfuscator.so` cannot be built.
- but then I tried to remove that line from `Transforms/CMakeLists.txt` and the test successfully ran, I've also checked the generated binaries and they seemed to be obfuscated fine.

I wonder how can the project be built successfully without that line, and does it affect the result if I remove it?
Thank you.

**Comment by bluesadi** [comment]
Hi, I'm not quite sure why this error occurred. Maybe it is because you didn't install LLVM to `/usr/bin` or `/usr/local/bin`.

About you question:
In `Transforms/CMakeLists.txt` line 20 `opt -lowerswitch -S IR/TestProgram_orig.ll -o IR/TestProgram_lowerswitch.ll` I used the lowerswitch Pass from libLLVMTransformUtils.so. However, it still worked fine without `link_libraries("libLLVMTransformUtils.so")`.
So that line is practically useless, you can remove it.

**Comment by lkmidas** [comment]
Thanks for the answer!
